#!/usr/bin/ruby

# this script do following jobs:
# - reads src/chrome/mock.html
# - extracts header part and content part
# - reads .embryo/firefox/data/frontend/wasavi.js
# - replaces "req.headHTML" to string literal of header part
# - repalces "req.bodyHTML" to string literal of content part
#

SRC_FILE = "src/chrome/mock.html"
DST_FILE = ".embryo/firefox/data/frontend/wasavi.js"

mock = '';
header = '';
content = '';

begin
	mock = File.read(SRC_FILE, :encoding => Encoding::UTF_8)
	mock = mock
		.gsub(/\n+/, '')
		.gsub(/<!--.*?-->/, '')
		.gsub(/<script[^>]*>.*?<\/script>/, '')
		.gsub(/>\s+</, '><')
		.gsub(/^\s+|\s+$/, '')
		.gsub(/'/, %q(\\\'))

	header = mock.match(/<head[^>]*>(.+?)<\/head>/)[1]
	content = mock.match(/<body[^>]*>(.+?)<\/body>/)[1]
rescue
	print "cannot read #{SRC_FILE}\n"
	exit 1
end

begin
	dst = File.read(DST_FILE, :encoding => Encoding::UTF_8)
	dst = dst
		.gsub(/(document\.head.innerHTML\s*=\s*)req\.headHTML/) {|match|
			Regexp.last_match[1] + "'" + header + "'"
		}
	dst = dst
		.gsub(/(document\.body.innerHTML\s*=\s*)req\.bodyHTML/) {|match|
			Regexp.last_match[1] + "'" + content + "'"
		}
	
	File.write(DST_FILE, dst, :encoding => Encoding::UTF_8)
rescue
	print "cannot read #{DST_FILE}\n"
	exit 1
end
