#!/usr/bin/php
<?php
$dir = "";
$base = "";
$out = "";

foreach ($argv as $arg) {
	if (preg_match('/^--dir=(.+)$/', $arg, $re)) {
		$dir = $re[1];
	}
	elseif (preg_match('/^--base=(.+)$/', $arg, $re)) {
		$base = $re[1];
	}
	elseif (preg_match('/^--out=(.+)$/', $arg, $re)) {
		$out = $re[1];
	}
}

if ($dir == "") {
	echo "missing directory.";
	exit(1);
}

if ($base != "") {
	$base = @filemtime($base);
	if ($base === false) {
		$base = 0;
	}
}
else {
	$base = 0;
}

if ($base) {
	echo "base timestamp: ", date("Y-m-d H:i:s", $base), "\n";
}
else {
	echo "base timestamp: (inavailable)\n";
}

$mtime = 0;
$mtimeFile = "";
function loop ($dir)
{
	global $mtime, $mtimeFile, $base;
	$handle = opendir($dir);
	if ($handle) {
		while (($f = readdir($handle)) !== false) {
			if ($f == "." || $f == "..") continue;

			$file = $dir . "/" . $f;
			if (is_dir($file)) {
				loop($file);
			}
			else {
				// ignore vim's swap file
				if (preg_match('/\.sw.$/', $file)) continue;

				if (filemtime($file) > $mtime) {
					$mtime = filemtime($file);
					$mtimeFile = $file;
				}
				if ($base && filemtime($file) > $base) {
					echo "newer: ", date("Y-m-d H:i:s", filemtime($file)), "\t", $file, "\n";
				}
			}
		}
		closedir($handle);
	}
}
loop($dir);

if ($out == "") {
	echo "last modified: ";
	echo date("Y-m-d H:i:s", $mtime);
	echo "\t", $mtimeFile, "\n";
}
else {
	touch($out, $mtime);
}
