#! /usr/bin/php
<?php
$dir = "";
$outdir = "";
$ver = "";
$strip_update_url = false;
$update_url = false;

foreach ($argv as $arg) {
	if (preg_match('/^--indir=(.+)$/', $arg, $re)) {
		$dir = $re[1];
	}
	elseif (preg_match('/^--outdir=(.+)$/', $arg, $re)) {
		$outdir = $re[1];
	}
	elseif (preg_match('/^--ver=(.+)$/', $arg, $re)) {
		$ver = $re[1];
	}
	elseif (preg_match('/^--strip-update-url$/', $arg, $re)) {
		$strip_update_url = true;
	}
	elseif (preg_match('/^--update-url=(.+)$/', $arg, $re)) {
		$update_url = $re[1];
	}
}

if ($dir == "") {
	echo "missing base directory.";
	exit(1);
}
if ($ver == "") {
	echo "missing version.";
	exit(1);
}

$content = @file_get_contents($dir . "/manifest.json");
if ($content === false) {
	echo "cannot read manifest.json";
	exit(1);
}

$content = json_decode($content, true);
$content["version"] = $ver;
if ($strip_update_url !== false) {
	unset($content["update_url"]);
}
if ($update_url !== false && isset($content["update_url"])) {
	$content["update_url"] = $update_url;
}

$content = json_encode($content, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

if ($outdir != "") {
    file_put_contents($outdir . "/manifest.json", $content);
}
else {
    echo mb_convert_encoding($content, "UTF-8", "UTF-8");
}

