#! /usr/bin/php
<?php
$dir = "";
$outdir = "";
$localedir = "";
$ver = "";
$strip_update_url = false;

foreach ($argv as $arg) {
	if (preg_match('/^--indir=(.+)$/', $arg, $re)) {
		$dir = $re[1];
	}
	elseif (preg_match('/^--ver=(.+)$/', $arg, $re)) {
		$ver = $re[1];
	}
	elseif (preg_match('/^--outdir=(.+)$/', $arg, $re)) {
		$outdir = $re[1];
	}
	elseif (preg_match('/^--localedir=(.+)$/', $arg, $re)) {
		$localedir = $re[1];
	}
	elseif (preg_match('/^--strip-update-url$/', $arg, $re)) {
		$strip_update_url = true;
	}
}

if ($dir == "") {
	echo "missing base directory.";
	exit(1);
}
if ($ver == "") {
	echo "missing version.";
	exit(1);
}

$xml = new SimpleXMLElement($dir . "/install.rdf", null, true);
$xml->registerXPathNamespace("RDF", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
$xml->registerXPathNamespace("em", "http://www.mozilla.org/2004/em-rdf#");

// set the version
$xml->Description[0]->version = $ver;

// set languaged description elements
if ($localedir != "") {
	$productName = $xml->xpath("/RDF:RDF/RDF:Description/em:name");

	$h = opendir($localedir);
	while (($file = readdir($h)) !== false) {
		if ($file == "." || $file == "..") continue;
		if (!is_dir($localedir . "/" .  $file)) continue;
		$message = json_decode(file_get_contents($localedir . "/" . $file . "/messages.json"));

		$localeCode = $file;
		$localeCode = preg_replace('/_/', '-', $localeCode);
		//$localeCode = strtolower($localeCode);

		$localized = $xml->Description[0]->addChild("em:localized", "", "http://www.mozilla.org/2004/em-rdf#");
		$desc = $localized->addChild("Description", "", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
		$desc->addChild("em:locale", $localeCode, "http://www.mozilla.org/2004/em-rdf#");
		$desc->addChild("em:name", (string)$productName[0], "http://www.mozilla.org/2004/em-rdf#");
		$desc->addChild("em:description", $message->wasavi_desc->message, "http://www.mozilla.org/2004/em-rdf#");
	}
	closedir($h);
}

// strip some attributes
if ($strip_update_url) {
	foreach ($xml->xpath("//em:updateURL") as $node) {
		unset($node[0]);
	}
}

$doc = new DOMDocument("1.0");
$doc->encoding = "UTF-8";
$doc->preserveWhiteSpace = false;
$doc->loadXML($xml->asXML());
$doc->formatOutput = true;
if ($outdir != "") {
	file_put_contents($outdir . "/install.rdf", $doc->saveXML());
}
else {
	echo mb_convert_encoding($doc->saveXML(), "UTF-8", "UTF-8");
}
